### PR TITLE
add support for multiple properties

### LINKED ISSUE #9: Add support for multiple properties
e.g `fullName: changeGate('firstName', 'lastName', function(firstName, lastName) { ..`

### PR DESCRIPTION
**Pull request by givanse**
Closes https://github.com/GavinJoyce/ember-computed-change-gate/issues/9

### CODE REVIEW

**Comment by GavinJoyce** [comment]
Thanks for the PR @givanse. Sorry, I must have missed it.

Perhaps you might rebase and resolve any conflicts? Thanks

**Comment by givanse** [comment]
No worries, I've seen in the Ember slack that you've been pretty busy.

Rebased.

**Comment by GavinJoyce** [comment]
Thanks! 🍻

**Comment by GavinJoyce** [comment]
https://github.com/GavinJoyce/ember-computed-change-gate/releases/tag/v1.0.2

**Pull request merged**
