### PR TITLE
Upgrade ember-cli 🆙

### PR DESCRIPTION
**Pull request by esbanarango**
This PR upgrades to the new modules API.

### CODE REVIEW

**Comment by GavinJoyce** [comment]
Hey, thanks. It looks like there are failing tests

**Comment by esbanarango** [comment]
Hey, yeah, current ember version of this project doesn't play well with the new modules API. I'll upgrade ember as well here.

**Comment by esbanarango** [comment]
@GavinJoyce Back to ✅.  👌

**Comment by GavinJoyce** [comment]
@esbanarango thank you!

**Comment by GavinJoyce** [comment]
https://github.com/GavinJoyce/ember-computed-change-gate/releases/tag/v1.0.3

**Pull request merged**
